apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: lilith-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: lilith-static-ip
    kubernetes.io/ingress.allow-http: "false"
spec:
  tls:
    - secretName: api-prod-tls
  backend:
    serviceName: lilith
    servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lilith
  labels:
    app: lilith
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: lilith
  type: NodePort

